---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: gitops-demo
spec:
  encryptedData:
    password: AgA6KB0VJTJDuHBg3/+QveU52LcP5C65Svq+q/bVG5urCxEF4Z2v0kZNMuaTsdpjH4PKY5/6fTp5Ido3ffyoDbxWDn28OZ1crD1CscCFE2wGftaCs8wRJjvnCmZ1T2as7sVSRZjnmCegzhUgSNg4quYNTEX+Vl+P6s7LF9fK0uazXAfys/SzmhAG9GU1oF/clAUkb8ODF9kay34mS+FyQ2X1yOOGG4b67VvUJCCQP32s3SOpN3q8BYBPHGF1nZm24pQizI7AWeqem1DGIOyzn26P3n/h6aNwDqlbGfjiGSpUgv/lxiC3uVUNpMQn9V/ONQVQ/kGcrQacPtKpo6+uJfjheOeLR5JJkn6RdgrdGULsOJpJp+1YsYZW+7B+VeMz1y81lls5T7SkljT8JMmd9kANJr+e8GuHyn0gCo1WHANo+G08uWkOgQKDn/GPxfl9/TWeHbEyWXhDDGNr64OdCwWcrCOod99ELCOhHCVoXpJRthXxNw/fhCkpBtay2pAPKkGW0iPbg8tp3zrU+Vm/akCkm94U6ewWyzZnLMo1AcU7yocyasI82KgHMn6axzc+LR7rzyFhwClbdmRChbmE+neiRjIZii2qfr6hZXHK1ByaS46O232BeitbgU7h+XFf9UXi9bX9dboaJreQ3nPDFm8Vx/fjqvIUiaS+VuisiZXDeJres6rZukALAsiLjlqZSlQ3qd63oSL585qD1X6Bz6I/4JY=
    username: AgCvEc1iwMNCdqmG5fvcjYbseggNYevb75+LRtGCkrk9PHHrMhZR46DjtoO+Zds8DX55DP7kB/FCzMsTbD5HI3xZ4YSGeXNV8/F3XP+c7FpulsyRSCb1DRmKtNRHae0225tEAY3EAr4/cSkwQ64TWoxQPlQ1/TK+3OKyRrtX+OrJJfuozJ7HIO1wjMj86JHidgDBUWQ0FTpdwl1vxExhAMGoBxC4ImWpSf8DRXELT6C2KjhESEDFxNZ85E5iOTGjKB8FAmYRy5YwmN12aZf3/o2gb+lMaRpIF02UKyAHBtxTfkI79BkuIfJsjNA/egMpTFvtym3/aJ8oAu5zPWZg3CWcR8SvgWJpSlEvlfNgN24BZK5o275cLMzYnci7Di5GhSB/OqRqxQvO27GywTBQRPi124YYJ6ve3JyYWk543FjM1tv9b7B3UCSegyOk1PODOpI0V/8pt2PenrRV09mYwIfDr8lLBsi45Q/FRBcRTeB8x86pHLd0ZQFFjaU44L+Wx/X3seYxTyj3HtDZQmjVtfaScFrIGZOJcTdYF6wDTR9yq5XopihrlnpxMwHoIEtaQLQVfwRA1V7V11KmFtO9NKpv/RKRU2KppKoImIHeewWEktI8dVo0GmLrcLu5FXex1TcqYoWo09BBBNGui2lNKs+EJMZxVAcqnyuqYRrEneX9BWW+uhrzRiz5jqheaAlMuA5yPLVEAIPu
  template:
    metadata:
      name: db-credentials
      namespace: gitops-demo
    type: Opaque
